//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unblock.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Unblock.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All files have been successfully unblocked ähnelt.
        /// </summary>
        internal static string AllFilesHaveBeenSuccessfullyUnblocked {
            get {
                return ResourceManager.GetString("AllFilesHaveBeenSuccessfullyUnblocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occurred:  ähnelt.
        /// </summary>
        internal static string AnErrorOccurred {
            get {
                return ResourceManager.GetString("AnErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to unblock the file. ähnelt.
        /// </summary>
        internal static string FailedToUnblockTheFile {
            get {
                return ResourceManager.GetString("FailedToUnblockTheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File is not blocked ähnelt.
        /// </summary>
        internal static string FileIsNotBlocked {
            get {
                return ResourceManager.GetString("FileIsNotBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File or folder not found ähnelt.
        /// </summary>
        internal static string FileOrFolderNotFound {
            get {
                return ResourceManager.GetString("FileOrFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File(s) Unblocked ähnelt.
        /// </summary>
        internal static string FileUnblocked {
            get {
                return ResourceManager.GetString("FileUnblocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insufficient permissions ähnelt.
        /// </summary>
        internal static string InsufficientPermissions {
            get {
                return ResourceManager.GetString("InsufficientPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Program registered in the context menu successfully. ähnelt.
        /// </summary>
        internal static string ProgramRegisteredInTheContextMenuSuccessfully {
            get {
                return ResourceManager.GetString("ProgramRegisteredInTheContextMenuSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Program unregistered from the context menu successfully. ähnelt.
        /// </summary>
        internal static string ProgramUnregisteredFromTheContextMenuSuccessfully {
            get {
                return ResourceManager.GetString("ProgramUnregisteredFromTheContextMenuSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File(s) successfully unblocked. ähnelt.
        /// </summary>
        internal static string TheFileHasBeenSuccessfullyUnblocked {
            get {
                return ResourceManager.GetString("TheFileHasBeenSuccessfullyUnblocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified file does not exist. ähnelt.
        /// </summary>
        internal static string TheSpecifiedFileDoesNotExist {
            get {
                return ResourceManager.GetString("TheSpecifiedFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified file is not blocked. ähnelt.
        /// </summary>
        internal static string TheSpecifiedFileIsNotBlocked {
            get {
                return ResourceManager.GetString("TheSpecifiedFileIsNotBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unblock File ähnelt.
        /// </summary>
        internal static string UnblockFile {
            get {
                return ResourceManager.GetString("UnblockFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon UnblockFileIcon {
            get {
                object obj = ResourceManager.GetObject("UnblockFileIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unblock files in folder ähnelt.
        /// </summary>
        internal static string UnblockFolder {
            get {
                return ResourceManager.GetString("UnblockFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Usage:	UnblockFile &lt;file or path&gt;
        ///	UnblockFile &lt;register&gt;
        ///	UnblockFile &lt;unregister&gt; ähnelt.
        /// </summary>
        internal static string UsageTunblockFile_pathNTunblockRegisterNTunblockUnregister {
            get {
                return ResourceManager.GetString("UsageTunblockFile_pathNTunblockRegisterNTunblockUnregister", resourceCulture);
            }
        }
    }
}
